---
name: 🐛 Bug Report
description: Report a bug or unexpected behavior in emp3r0r
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

        **Note**: For security vulnerabilities, please follow our security policy and report privately.

        ---

        💖 **Support the Project**: If emp3r0r has been helpful to you, consider [sponsoring the project](https://github.com/sponsors/jm33-m0) to support ongoing development and maintenance!

        ⚡ **Want faster bug fixes?** Sponsors get priority support and faster issue resolution!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues for duplicates
          required: true
        - label: This is not a question (use the question template instead)
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: input
    id: version
    attributes:
      label: emp3r0r Version
      description: What version of emp3r0r are you using?
      placeholder: "e.g., v2.4.0, latest commit hash, or 'built from source' (which commit?)"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - C2 Server
        - Agent
        - Modules
        - Installation/Build
        - Documentation
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please run the following commands and paste the output to provide reliable version information:

        **For Unix/Linux/macOS:**
        ```bash
        uname -a
        cat /etc/os-release 2>/dev/null || sw_vers 2>/dev/null
        go version
        ```

        **For Windows:**
        ```cmd
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
        echo %PROCESSOR_ARCHITECTURE%
        go version
        ```

        **Additional info (if relevant):** Network setup, virtualization platform, container runtime
      placeholder: "Paste command output here..."
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide detailed, numbered steps to reproduce the behavior. Be as specific as possible.
        Include commands, configuration details, and any relevant setup information.
      placeholder: |
        1. Start emp3r0r with configuration...
        2. Run command...
        3. Observe that...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: logs-output
    attributes:
      label: Logs and Output
      description: |
        Paste relevant logs, error messages, or command output here.

        **Important:** Use code blocks (```) for formatting and remember to redact any sensitive information like passwords, API keys, hostnames, or IP addresses!
      placeholder: "Paste logs and output here..."
      render: text

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Share relevant parts of your configuration files, command line arguments, environment variables, etc.

        **⚠️ Security Notice:** Make sure to remove any sensitive information like passwords, API keys, certificates, or internal network details before posting!
      placeholder: "Paste relevant configuration here..."
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context that might help us understand and reproduce the problem:
        - Screenshots or recordings (if applicable)
        - Workarounds you've tried
        - Related issues or discussions
        - Network topology or setup details
        - Timeline of when the issue started
        - Hardware specifications (if performance-related)
      placeholder: "Any additional context, screenshots, or relevant information..."

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe is this bug?
      options:
        - Critical - Complete system failure
        - High - Major functionality broken
        - Medium - Some features affected
        - Low - Minor inconvenience
        - Cosmetic - UI/display issues
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help?
      options:
        - label: I am willing to submit a pull request to fix this bug
        - label: I can help test the fix once available
        - label: I can provide additional debugging information if needed
